region              = "us-east-1"
cidr_block          = "10.0.0.0/16"
subnet_cidr_block   = "10.0.0.0/24"
availability_zone   = "us-east-1a"
rt_cidr_block       = "0.0.0.0/0"
sg_cidr_block       = "0.0.0.0/0"  
instance_type       = "t2.micro"
key_name            = "my-key"